// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2557.SOTABots2015;
    


import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveTrainFrontLeft;
    public static SpeedController driveTrainFrontRight;
    public static SpeedController driveTrainBackLeft;
    public static SpeedController driveTrainBackRight;
    public static RobotDrive driveTrainRobotDrive41;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static Gyro locationGyro;
    public static AnalogAccelerometer locationAccelerometer;
    public static Encoder flEncoder;//Front Left Encoder
    public static Encoder frEncoder;//Front Right Encoder
    public static Encoder brEncoder;//Back Right Encoder
    public static Encoder blEncoder;//Back Left Encoder
    public static Ultrasonic rangeLeft1;
    public static Ultrasonic rangeLeft2;
    public static Ultrasonic rangeRight1;
    public static Ultrasonic rangeRight2;
    public static Ultrasonic rangeBack1;
    public static Ultrasonic rangeBack2;
    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    	driveTrainFrontLeft = new Talon(0);
        LiveWindow.addActuator("DriveTrain", "FrontLeft", (Talon) driveTrainFrontLeft);
        
        driveTrainFrontRight = new Talon(1);
        LiveWindow.addActuator("DriveTrain", "FrontRight", (Talon) driveTrainFrontRight);
        
        driveTrainBackLeft = new Talon(2);
        LiveWindow.addActuator("DriveTrain", "BackLeft", (Talon) driveTrainBackLeft);
        
        driveTrainBackRight = new Talon(3);
        LiveWindow.addActuator("DriveTrain", "BackRight", (Talon) driveTrainBackRight);
        
        driveTrainRobotDrive41 = new RobotDrive(driveTrainFrontLeft, driveTrainBackLeft,
        		driveTrainFrontRight, driveTrainBackRight);
        
//Encoder Ports
        flEncoder = new Encoder(0,0);
        frEncoder = new Encoder(0,0);
        blEncoder = new Encoder(0,0);
        brEncoder = new Encoder(0,0);
        
//Range Finder Ports
        rangeLeft1 = new Ultrasonic(0,0);
        rangeLeft2 = new Ultrasonic(0,0);
        rangeBack1 = new Ultrasonic(0,0);
        rangeBack2 = new Ultrasonic(0,0);
        rangeRight1 = new Ultrasonic(0,0);
        rangeRight2 = new Ultrasonic(0,0);

//Gyro Ports & Sensitivity
        locationGyro = new Gyro(0);
        LiveWindow.addSensor("Location", "Gyro", locationGyro);
        locationGyro.setSensitivity(0.007);
        
//Accelerometer Ports & Sensitivity
        locationAccelerometer = new AnalogAccelerometer(1);
        LiveWindow.addSensor("Location", "Accelerometer", locationAccelerometer);
        locationAccelerometer.setSensitivity(0.0);
        locationAccelerometer.setZero(2.5);
        
//Drive Train Sensitivity, Max Output, and Inversions
        driveTrainRobotDrive41.setSafetyEnabled(true);
        driveTrainRobotDrive41.setExpiration(0.1);
        driveTrainRobotDrive41.setSensitivity(0.5);
        driveTrainRobotDrive41.setMaxOutput(1.0);
        driveTrainRobotDrive41.setInvertedMotor(RobotDrive.MotorType.kFrontLeft, true);
        driveTrainRobotDrive41.setInvertedMotor(RobotDrive.MotorType.kRearLeft, true);
        

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
