// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2557.SOTABots2015;
    
import edu.wpi.first.wpilibj.*;

import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveWithJoystickFrontLeft;
    public static SpeedController driveWithJoystickFrontRight;
    public static SpeedController driveWithJoystickBackLeft;
    public static SpeedController driveWithJoystickBackRight;
    public static RobotDrive driveWithJoystickRobotDrive41;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveWithJoystickFrontLeft = new Talon(0);
        LiveWindow.addActuator("DriveWithJoystick", "FrontLeft", (Talon) driveWithJoystickFrontLeft);
        
        driveWithJoystickFrontRight = new Talon(1);
        LiveWindow.addActuator("DriveWithJoystick", "FrontRight", (Talon) driveWithJoystickFrontRight);
        
        driveWithJoystickBackLeft = new Talon(2);
        LiveWindow.addActuator("DriveWithJoystick", "BackLeft", (Talon) driveWithJoystickBackLeft);
        
        driveWithJoystickBackRight = new Talon(3);
        LiveWindow.addActuator("DriveWithJoystick", "BackRight", (Talon) driveWithJoystickBackRight);
        
        driveWithJoystickRobotDrive41 = new RobotDrive(driveWithJoystickFrontLeft, driveWithJoystickBackLeft,
              driveWithJoystickFrontRight, driveWithJoystickBackRight);
        
        driveWithJoystickRobotDrive41.setSafetyEnabled(true);
        driveWithJoystickRobotDrive41.setExpiration(0.1);
        driveWithJoystickRobotDrive41.setSensitivity(0.5);
        driveWithJoystickRobotDrive41.setMaxOutput(1.0);

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
